//! Emits `types.rs` — DTO and input structs for a BC.

use crate::model::{ResolvedField, ResolvedParam, ResolvedQuery};

pub fn emit(bc: &str, queries: &[ResolvedQuery]) -> String {
    let mut out = String::new();
    out.push_str(&header(bc));

    // Collect all DTOs and input structs, deduplicate by name
    let mut seen = std::collections::HashSet::new();

    for q in queries {
        // DTO for read queries
        if let Some(dto_name) = &q.dto_name {
            if seen.insert(dto_name.clone()) {
                out.push_str(&emit_dto(dto_name, &q.row_fields));
            }
        }

        // Input struct for exec with input
        if let Some(input_name) = &q.input_name {
            if seen.insert(input_name.clone()) {
                out.push_str(&emit_input(input_name, &q.params));
            }
        }
    }

    out
}

fn header(bc: &str) -> String {
    format!(
        "// This file was generated by `repo-gen`. Do not modify.\n\
         // BC: {bc}\n\
         \n\
         #![allow(dead_code)]\n\
         \n"
    )
}

fn emit_dto(name: &str, fields: &[ResolvedField]) -> String {
    let mut out = String::new();
    out.push_str(&format!("#[derive(Debug)]\npub struct {name} {{\n"));
    for f in fields {
        out.push_str(&format!("    pub {}: {},\n", f.name, f.domain_type));
    }
    out.push_str("}\n\n");
    out
}

fn emit_input(name: &str, params: &[ResolvedParam]) -> String {
    let mut out = String::new();
    out.push_str(&format!("#[derive(Debug)]\npub struct {name} {{\n"));
    for p in params {
        // Input struct uses owned types (not references)
        let owned = to_owned_type(&p.domain_type);
        out.push_str(&format!("    pub {}: {},\n", p.name, owned));
    }
    out.push_str("}\n\n");
    out
}

fn to_owned_type(ty: &str) -> String {
    match ty {
        "&str" => "String".to_string(),
        "&bigdecimal::BigDecimal" => "bigdecimal::BigDecimal".to_string(),
        t if t.starts_with('&') => t[1..].to_string(),
        t => t.to_string(),
    }
}
