//! Emits `mod.rs` with BC facade struct and re-exports.

use std::collections::BTreeSet;

use heck::ToUpperCamelCase;

pub fn emit(bc: &str, repo_names: &BTreeSet<String>) -> String {
    let facade_name = format!("{}Db", bc.to_upper_camel_case());
    let mut out = String::new();

    // Header
    out.push_str(&format!(
        "// This file was generated by `repo-gen`. Do not modify.\n\
         // BC: {bc}\n\
         \n"
    ));

    // Module declarations
    out.push_str("pub mod types;\n");
    for name in repo_names {
        out.push_str(&format!("pub mod {name};\n"));
    }
    out.push('\n');

    // Re-exports
    out.push_str("pub use types::*;\n");
    for name in repo_names {
        let struct_name = format!("{}Repo", name.to_upper_camel_case());
        out.push_str(&format!("pub use {name}::{struct_name};\n"));
    }
    out.push('\n');

    // Facade struct
    out.push_str(&format!("pub struct {facade_name}<'a> {{\n"));
    for name in repo_names {
        let struct_name = format!("{}Repo", name.to_upper_camel_case());
        out.push_str(&format!("    pub {name}: {struct_name}<'a>,\n"));
    }
    out.push_str("}\n\n");

    // Facade impl
    out.push_str(&format!(
        "impl<'a> {facade_name}<'a> {{\n\
         \x20   #[must_use]\n\
         \x20   pub fn new(client: &'a deadpool_postgres::Client, tenant_id: kernel::types::TenantId) -> Self {{\n\
         \x20       Self {{\n"
    ));
    for name in repo_names {
        let struct_name = format!("{}Repo", name.to_upper_camel_case());
        out.push_str(&format!(
            "            {name}: {struct_name}::new(client, tenant_id),\n"
        ));
    }
    out.push_str(
        "        }\n\
         \x20   }\n\
         }\n",
    );

    out
}
