//! Emits per-repo-group files with struct + methods.

use std::collections::BTreeSet;

use heck::ToUpperCamelCase;

use crate::model::{ResolvedParam, ResolvedQuery};
use crate::sql_parser::QueryKind;

pub fn emit(bc: &str, repo_name: &str, queries: &[&ResolvedQuery]) -> String {
    let struct_name = format!("{}Repo", repo_name.to_upper_camel_case());
    let mut out = String::new();
    let type_imports = collect_type_imports(queries);

    // Header
    out.push_str(&format!(
        "// This file was generated by `repo-gen`. Do not modify.\n\
         // BC: {bc}, repo: {repo_name}\n\
         \n\
         use kernel::AppError;\n\
         use kernel::types::TenantId;\n"
    ));
    if !type_imports.is_empty() {
        out.push_str(&format!(
            "use super::types::{{{}}};\n",
            type_imports.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    out.push('\n');

    // Struct
    out.push_str(&format!(
        "pub struct {struct_name}<'a> {{\n\
         \x20   client: &'a deadpool_postgres::Client,\n\
         \x20   tenant_id: TenantId,\n\
         }}\n\
         \n\
         impl<'a> {struct_name}<'a> {{\n\
         \x20   #[must_use]\n\
         \x20   pub fn new(client: &'a deadpool_postgres::Client, tenant_id: TenantId) -> Self {{\n\
         \x20       Self {{ client, tenant_id }}\n\
         \x20   }}\n\
         }}\n\
         \n"
    ));

    // Methods
    out.push_str(&format!("impl {struct_name}<'_> {{\n"));
    for q in queries {
        out.push_str(&emit_method(q));
    }
    out.push_str("}\n");

    out
}

fn emit_method(q: &ResolvedQuery) -> String {
    match q.kind {
        QueryKind::Exec => {
            if q.input_name.is_some() {
                emit_exec_with_input(q)
            } else {
                emit_exec(q)
            }
        }
        QueryKind::Opt => emit_read(q, "opt", "Option"),
        QueryKind::One => emit_read(q, "one", "One"),
        QueryKind::All => emit_read(q, "all", "Vec"),
    }
}

fn emit_exec(q: &ResolvedQuery) -> String {
    let mut out = String::new();
    let params_sig = method_params_signature(&q.params);
    let bind_args = bind_args(&q.params);

    out.push_str(&doc_comment(q, false));
    out.push_str(&format!(
        "    pub async fn {name}(&self{params_sig}) -> Result<(), AppError> {{\n\
         \x20       use kernel::IntoInternal;\n\
         \x20       {clorinde_fn}()\n\
         \x20           .bind(self.client, &db::conversions::tid(self.tenant_id){bind_args})\n\
         \x20           .await\n\
         \x20           .internal(\"{name}\")?;\n\
         \x20       Ok(())\n\
         \x20   }}\n\
         \n",
        name = q.name,
        clorinde_fn = q.clorinde_fn,
    ));

    out
}

fn emit_exec_with_input(q: &ResolvedQuery) -> String {
    let input_name = q.input_name.as_ref().unwrap();
    let mut out = String::new();

    // Build bind args from input struct fields
    let bind_args = q
        .params
        .iter()
        .map(|p| {
            if p.needs_dec_str {
                format!(", &db::transport::DecStr(&input.{})", p.name)
            } else {
                format!(", &input.{}", p.name)
            }
        })
        .collect::<String>();

    out.push_str(&doc_comment(q, false));
    out.push_str(&format!(
        "    pub async fn {name}(&self, input: &{input_name}) -> Result<(), AppError> {{\n\
         \x20       use kernel::IntoInternal;\n\
         \x20       {clorinde_fn}()\n\
         \x20           .bind(self.client, &db::conversions::tid(self.tenant_id){bind_args})\n\
         \x20           .await\n\
         \x20           .internal(\"{name}\")?;\n\
         \x20       Ok(())\n\
         \x20   }}\n\
         \n",
        name = q.name,
        clorinde_fn = q.clorinde_fn,
    ));

    out
}

fn emit_read(q: &ResolvedQuery, _call_method: &str, wrapper: &str) -> String {
    let dto_name = q.dto_name.as_ref().unwrap();
    let params_sig = method_params_signature(&q.params);
    let bind_args = bind_args(&q.params);
    let mut out = String::new();

    let return_type = match wrapper {
        "Option" => format!("Option<{dto_name}>"),
        "Vec" => format!("Vec<{dto_name}>"),
        "One" => dto_name.to_string(),
        _ => unreachable!(),
    };

    out.push_str(&doc_comment(q, wrapper == "One"));
    out.push_str(&format!(
        "    pub async fn {name}(&self{params_sig}) -> Result<{return_type}, AppError> {{\n\
         \x20       use kernel::IntoInternal;\n",
        name = q.name,
    ));

    match wrapper {
        "Option" => {
            out.push_str(&format!(
                "        let row = {clorinde_fn}()\n\
                 \x20           .bind(self.client, &db::conversions::tid(self.tenant_id){bind_args})\n\
                 \x20           .opt()\n\
                 \x20           .await\n\
                 \x20           .internal(\"{name}\")?;\n\
                 \x20       match row {{\n\
                 \x20           Some(r) => Ok(Some({mapping})),\n\
                 \x20           None => Ok(None),\n\
                 \x20       }}\n",
                clorinde_fn = q.clorinde_fn,
                name = q.name,
                mapping = emit_row_mapping(dto_name, &q.row_fields, &q.name),
            ));
        }
        "One" => {
            out.push_str(&format!(
                "        let row = {clorinde_fn}()\n\
                 \x20           .bind(self.client, &db::conversions::tid(self.tenant_id){bind_args})\n\
                 \x20           .opt()\n\
                 \x20           .await\n\
                 \x20           .internal(\"{name}\")?;\n\
                 \x20       match row {{\n\
                 \x20           Some(r) => Ok({mapping}),\n\
                 \x20           None => Err(kernel::AppError::Domain(\n\
                 \x20               kernel::DomainError::NotFound(\"{name}\".to_string())\n\
                 \x20           )),\n\
                 \x20       }}\n",
                clorinde_fn = q.clorinde_fn,
                name = q.name,
                mapping = emit_row_mapping(dto_name, &q.row_fields, &q.name),
            ));
        }
        "Vec" => {
            out.push_str(&format!(
                "        let rows = {clorinde_fn}()\n\
                 \x20           .bind(self.client, &db::conversions::tid(self.tenant_id){bind_args})\n\
                 \x20           .all()\n\
                 \x20           .await\n\
                 \x20           .internal(\"{name}\")?;\n\
                 \x20       rows.into_iter()\n\
                 \x20           .map(|r| Ok({mapping}))\n\
                 \x20           .collect::<Result<Vec<_>, AppError>>()\n",
                clorinde_fn = q.clorinde_fn,
                name = q.name,
                mapping = emit_row_mapping(dto_name, &q.row_fields, &q.name),
            ));
        }
        _ => unreachable!(),
    }

    out.push_str("    }\n\n");
    out
}

fn collect_type_imports(queries: &[&ResolvedQuery]) -> BTreeSet<String> {
    let mut imports = BTreeSet::new();
    for q in queries {
        if let Some(dto_name) = &q.dto_name {
            imports.insert(dto_name.clone());
        }
        if let Some(input_name) = &q.input_name {
            imports.insert(input_name.clone());
        }
    }
    imports
}

fn doc_comment(q: &ResolvedQuery, can_not_found: bool) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "    /// SQL: `queries/{bc}/{file}.sql --! {name}`\n\
         \x20   ///\n\
         \x20   /// # Errors\n\
         \x20   ///\n\
         \x20   /// Returns [`AppError::Internal`] when the SQL call or row conversion fails.\n",
        bc = q.bc,
        file = q.file_stem,
        name = q.name,
    ));
    if can_not_found {
        out.push_str(
            "    /// Returns [`AppError::Domain`] with `NotFound` when the query expects one row and none match.\n",
        );
    }
    out
}

fn emit_row_mapping(
    dto_name: &str,
    fields: &[crate::model::ResolvedField],
    query_name: &str,
) -> String {
    let field_mappings: Vec<String> = fields
        .iter()
        .map(|f| {
            if f.needs_parse_dec {
                format!(
                    "{name}: db::conversions::parse_dec(&r.{name}).internal(\"{query_name}\")?",
                    name = f.name,
                )
            } else {
                format!("{name}: r.{name}", name = f.name)
            }
        })
        .collect();

    format!(
        "{dto_name} {{ {fields} }}",
        fields = field_mappings.join(", "),
    )
}

/// Build method parameter signature (`, name: Type, ...`).
fn method_params_signature(params: &[ResolvedParam]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let parts: Vec<String> = params
        .iter()
        .map(|p| format!("{}: {}", p.name, p.domain_type))
        .collect();
    format!(", {}", parts.join(", "))
}

/// Build bind arguments string (`, &arg, ...`).
fn bind_args(params: &[ResolvedParam]) -> String {
    params
        .iter()
        .map(|p| {
            if p.needs_dec_str {
                format!(", &db::transport::DecStr({})", p.name)
            } else if p.is_string_sql {
                format!(", &{}", p.name)
            } else {
                format!(", {}", p.name)
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::emit;
    use crate::model::{ResolvedField, ResolvedParam, ResolvedQuery};
    use crate::sql_parser::QueryKind;

    fn sample_exec() -> ResolvedQuery {
        ResolvedQuery {
            bc: "warehouse".to_string(),
            file_stem: "inventory".to_string(),
            name: "create_item".to_string(),
            repo_group: "inventory".to_string(),
            kind: QueryKind::Exec,
            dto_name: None,
            input_name: None,
            params: vec![
                ResolvedParam {
                    name: "id".to_string(),
                    domain_type: "&uuid::Uuid".to_string(),
                    needs_dec_str: false,
                    is_string_sql: false,
                },
                ResolvedParam {
                    name: "sku".to_string(),
                    domain_type: "&str".to_string(),
                    needs_dec_str: false,
                    is_string_sql: true,
                },
            ],
            row_fields: Vec::new(),
            clorinde_fn: "clorinde_gen::queries::warehouse::inventory::create_item".to_string(),
        }
    }

    fn sample_read() -> ResolvedQuery {
        ResolvedQuery {
            bc: "warehouse".to_string(),
            file_stem: "balances".to_string(),
            name: "get_balance".to_string(),
            repo_group: "balances".to_string(),
            kind: QueryKind::Opt,
            dto_name: Some("BalanceRow".to_string()),
            input_name: None,
            params: vec![ResolvedParam {
                name: "sku".to_string(),
                domain_type: "&str".to_string(),
                needs_dec_str: false,
                is_string_sql: true,
            }],
            row_fields: vec![
                ResolvedField {
                    name: "item_id".to_string(),
                    domain_type: "uuid::Uuid".to_string(),
                    needs_parse_dec: false,
                },
                ResolvedField {
                    name: "balance".to_string(),
                    domain_type: "bigdecimal::BigDecimal".to_string(),
                    needs_parse_dec: true,
                },
            ],
            clorinde_fn: "clorinde_gen::queries::warehouse::balances::get_balance".to_string(),
        }
    }

    #[test]
    fn generated_repo_uses_explicit_imports_and_errors_docs() {
        let read = sample_read();
        let code = emit("warehouse", "balances", &[&read]);

        assert!(code.contains("use super::types::{BalanceRow};"));
        assert!(!code.contains("use super::types::*;"));
        assert!(code.contains("/// # Errors"));
        assert!(code.contains("Returns [`AppError::Internal`]"));
        assert!(code.contains("SQL: `queries/warehouse/balances.sql --! get_balance`"));
    }

    #[test]
    fn generated_repo_skips_type_imports_when_unused() {
        let exec = sample_exec();
        let code = emit("warehouse", "inventory", &[&exec]);

        assert!(!code.contains("use super::types::{"));
    }
}
